### ISSUE TITLE
bug: deploy example ERC20 token doesnt work

### ISSUE THREAD

**Issue by mburger81** [bitfinity-network/bitfinity-evm-examples#9]
Today we tried to deploy our token and our contracts on your bitfinity EVM test chain but we run into an issue.

So we tried to deploy your `Watermelon.sol` test `ERC20` token, we had to add the `timeout` in the `hardhat.config.js` but at the end we run into the exactly same issue with our Token and contracts

```
yarn hardhat run scripts/deploy.js --network testnet_bitfinity
Deploying contracts with the account: 0x88fa1Bc4643116500148206F1F61d32c1d24F355
Account balance: 30000000000000000000
HardhatError: HH110: Invalid JSON-RPC response received:
<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>502 Server Error</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Server Error</h1>
<h2>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.</h2>
<h2></h2>
</body></html>

    at parseJsonResponse (/Users/mburger/software/workspace/helix/bitfinity-evm-examples/hardhat/erc20/node_modules/hardhat/src/internal/util/jsonrpc.ts:47:11)
    at HttpProvider._fetchJsonRpcResponse (/Users/mburger/software/workspace/helix/bitfinity-evm-examples/hardhat/erc20/node_modules/hardhat/src/internal/core/providers/http.ts:218:31)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at HttpProvider.request (/Users/mburger/software/workspace/helix/bitfinity-evm-examples/hardhat/erc20/node_modules/hardhat/src/internal/core/providers/http.ts:85:29)
    at EthersProviderWrapper.send (/Users/mburger/software/workspace/helix/bitfinity-evm-examples/hardhat/erc20/node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:20)
```

**Comment by mburger81** [comment]
@itsyaasir @alexriet can maybe someone of you have a look on this issue?
Thx you so much

**Comment by sukanto1mm** [comment]
nice1
